/*
 * Copyright 2025 Julien Bombled
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// src/js/ui/render.js - Rendu des résultats et cartes
import { getElement } from './dom.js';
import { copyToClipboard } from '../utils/clipboard.js';
import { showToast } from '../utils/toast.js';
import { compositionCounts, escapeHtml } from '../utils/helpers.js';
import { safeLog } from '../utils/logger.js';
import { sanitizeHTML } from '../utils/dom-sanitizer.js';
import { VaultBridge } from './vault-bridge.js';
import { SaveToVaultModal } from './save-to-vault-modal.js';
import { checkPasswordBreach, formatBreachCount, getBreachSeverity } from '../utils/breach-check.js';

const clickTimers = new WeakMap();
let eventController = new AbortController();

export function renderResults(results, mask) {
  const wrap = getElement('#results-list');
  if (!wrap) return;

  try {
    cleanupPasswordListeners();
    wrap.innerHTML = sanitizeHTML('');

    if (!Array.isArray(results) || results.length === 0) {
      wrap.innerHTML = sanitizeHTML(`
        <div class="empty-state">
          <div class="empty-icon">🔐</div>
          <p>Cliquez sur "Générer" pour créer vos mots de passe</p>
        </div>`);
      return;
    }

    // PERFORMANCE: Use DocumentFragment to batch DOM updates
    // This reduces reflows from O(n) to O(1) when rendering multiple passwords
    const fragment = document.createDocumentFragment();

    results.forEach((item, idx) => {
      const { value } = item;
      if (typeof value !== 'string') return;

      const card = createPasswordCard(item, idx + 1, mask);
      fragment.appendChild(card);
    });

    // Single DOM update instead of n updates
    wrap.appendChild(fragment);

    bindPasswordClickEvents();
  } catch (e) {
    safeLog(`Erreur renderResults: ${e.message}`);
  }
}

function createPasswordCard(item, id, mask) {
  // Null guard for invalid items
  if (!item?.value || typeof item.value !== 'string') {
    const placeholder = document.createElement('div');
    placeholder.className = 'card card-error';
    placeholder.textContent = 'Invalid password data';
    return placeholder;
  }

  const { value, entropy, mode, dictionary } = item;
  const counts = compositionCounts(value);
  const total = value.length || 1;

  // Calcul des segments pour la barre de composition
  const segU = Math.round(counts.U / total * 1000) / 10;
  const segL = Math.round(counts.L / total * 1000) / 10;
  const segD = Math.round(counts.D / total * 1000) / 10;
  const segS = Math.round(counts.S / total * 1000) / 10;

  // Information sur le dictionnaire
  const dictInfo = mode === 'passphrase' && dictionary ?
    `${dictionary.charAt(0).toUpperCase() + dictionary.slice(1)}` :
    mode || 'unknown';

  // Vault save button (only visible in Electron)
  const vaultAvailable = VaultBridge.isAvailable();
  const saveToVaultBtn = vaultAvailable ? `
    <button class="action-btn save-to-vault-btn" type="button" data-password="${escapeHtml(value)}" title="Sauvegarder" aria-label="Sauvegarder dans le coffre">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
        <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
      </svg>
    </button>
  ` : '';

  const card = document.createElement('div');
  card.className = 'card';
  // Note: No sanitizeHTML here - all dynamic content is already escaped with escapeHtml()
  // The structure is static HTML generated by our code, not user input
  card.innerHTML = `
    <div class="card-sec card-header">
      <div class="id">#${id}</div>
      <span class="spacer"></span>
      <div class="stat"><span class="dot"></span><strong>${(entropy || 0).toFixed(1)}</strong>&nbsp;bits</div>
      <div class="len">${total} chars</div>
    </div>
    <div class="card-sec pwd ${mask ? 'masked' : ''}" data-index="${id-1}" data-password="${escapeHtml(value)}" title="Cliquer pour copier • Double-clic pour afficher/masquer">
      <div class="value mono">${escapeHtml(value)}</div>
      <div class="actions">
        <button class="action-btn breach-check-btn" type="button" data-password="${escapeHtml(value)}" title="Vérifier les fuites">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
          </svg>
        </button>
        ${saveToVaultBtn}
        <button class="action-btn copy-btn" type="button" title="Copier">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
          </svg>
        </button>
      </div>
      <div class="breach-status" hidden></div>
    </div>
    <div class="card-sec comp">
      <div class="comp-bar">
        ${segU > 0 ? `<div class="seg u" data-width="${segU}"></div>` : ''}
        ${segL > 0 ? `<div class="seg l" data-width="${segL}"></div>` : ''}
        ${segD > 0 ? `<div class="seg d" data-width="${segD}"></div>` : ''}
        ${segS > 0 ? `<div class="seg s" data-width="${segS}"></div>` : ''}
      </div>
      <div class="comp-legend">
        <span class="legend-item"><span class="legend-dot u"></span>${counts.U} MAJ</span>
        <span class="legend-item"><span class="legend-dot l"></span>${counts.L} min</span>
        <span class="legend-item"><span class="legend-dot d"></span>${counts.D} chiffres</span>
        <span class="legend-item"><span class="legend-dot s"></span>${counts.S} spé</span>
      </div>
    </div>
    <div class="card-sec info"><div>Mode: ${dictInfo}</div><div>CLI-Safe: ✓</div></div>
  `;

  // Apply widths via CSS custom properties (CSP-compliant)
  const compBar = card.querySelector('.comp-bar');
  if (compBar) {
    const segments = compBar.querySelectorAll('.seg');
    segments.forEach(seg => {
      const width = seg.getAttribute('data-width');
      if (width) {
        seg.style.setProperty('--seg-width', `${width}%`);
      }
    });
  }

  return card;
}

function bindPasswordClickEvents() {
  const passwordElements = document.querySelectorAll('.pwd');

  passwordElements.forEach(el => {
    // Click on password area (not on buttons)
    el.addEventListener('click', async (e) => {
      // Don't trigger if clicking on buttons
      if (e.target.closest('.save-to-vault-btn') || e.target.closest('.copy-btn') || e.target.closest('.breach-check-btn')) {
        return;
      }

      e.preventDefault();

      const existingTimer = clickTimers.get(el);
      if (existingTimer) {
        clearTimeout(existingTimer);
        clickTimers.delete(el);

        // Double-clic : basculer masquage
        el.classList.toggle('masked');
        return;
      }

      // Simple clic : programmer la copie
      const timer = setTimeout(async () => {
        try {
          clickTimers.delete(el);

          const password = el.getAttribute('data-password');
          if (password) {
            el.classList.add('copying');

            const success = await copyToClipboard(password);
            if (success) {
              showToast('Mot de passe copié !', 'success');
              safeLog(`Copié: ${password.substring(0, 8)}...`);
            } else {
              showToast('Erreur lors de la copie', 'error');
            }

            setTimeout(() => {
              el.classList.remove('copying');
            }, 600);
          }
        } catch (err) {
          safeLog('Copy to clipboard failed:', err);
        }
      }, 250);

      clickTimers.set(el, timer);
    }, { signal: eventController.signal });

    // Context menu (right-click)
    el.addEventListener('contextmenu', (e) => {
      e.preventDefault();
      const password = el.getAttribute('data-password');
      if (password) {
        showContextMenu(e, password);
      }
    }, { signal: eventController.signal });
  });

  // Bind save-to-vault buttons
  bindSaveToVaultButtons();

  // Bind copy buttons
  bindCopyButtons();

  // Bind breach check buttons
  bindBreachCheckButtons();

  safeLog(`Bound click events to ${passwordElements.length} password cards`);
}

/**
 * Bind save-to-vault button click events
 */
function bindSaveToVaultButtons() {
  const saveButtons = document.querySelectorAll('.save-to-vault-btn');

  saveButtons.forEach(btn => {
    btn.addEventListener('click', async (e) => {
      e.preventDefault();
      e.stopPropagation();

      const password = btn.getAttribute('data-password');
      if (password) {
        await SaveToVaultModal.open(password);
      }
    }, { signal: eventController.signal });
  });
}

/**
 * Bind copy button click events
 */
function bindCopyButtons() {
  const copyButtons = document.querySelectorAll('.copy-btn');

  copyButtons.forEach(btn => {
    btn.addEventListener('click', async (e) => {
      e.preventDefault();
      e.stopPropagation();

      const pwdEl = btn.closest('.pwd');
      const password = pwdEl?.getAttribute('data-password');

      if (password) {
        pwdEl.classList.add('copying');

        const success = await copyToClipboard(password);
        if (success) {
          showToast('Mot de passe copié !', 'success');
          btn.classList.add('copied');
          setTimeout(() => btn.classList.remove('copied'), 1000);
        } else {
          showToast('Erreur lors de la copie', 'error');
        }

        setTimeout(() => {
          pwdEl.classList.remove('copying');
        }, 600);
      }
    }, { signal: eventController.signal });
  });
}

/**
 * Bind breach check button click events
 */
function bindBreachCheckButtons() {
  const breachButtons = document.querySelectorAll('.breach-check-btn');

  breachButtons.forEach(btn => {
    btn.addEventListener('click', async (e) => {
      e.preventDefault();
      e.stopPropagation();

      const password = btn.getAttribute('data-password');
      if (!password) return;

      // Get the status element in the same card
      const card = btn.closest('.pwd');
      const statusEl = card?.querySelector('.breach-status');
      if (!statusEl) return;

      // Show loading state
      btn.classList.add('checking');
      btn.disabled = true;
      statusEl.hidden = false;
      statusEl.className = 'breach-status loading';
      statusEl.innerHTML = '<span class="breach-spinner"></span> Vérification...';

      try {
        const result = await checkPasswordBreach(password);

        if (result.error) {
          statusEl.className = 'breach-status error';
          statusEl.innerHTML = `<span class="breach-icon">⚠️</span> Erreur: ${result.error}`;
        } else if (result.breached) {
          const severity = getBreachSeverity(result.count);
          const countText = formatBreachCount(result.count);
          statusEl.className = `breach-status ${severity}`;
          statusEl.innerHTML = `<span class="breach-icon">🚨</span> ${countText}`;
          showToast(`Mot de passe compromis ! (${countText})`, 'error', 5000);
        } else {
          statusEl.className = 'breach-status safe';
          statusEl.innerHTML = '<span class="breach-icon">✅</span> Non compromis';
          showToast('Mot de passe non trouvé dans les fuites connues', 'success');
        }
      } catch (err) {
        statusEl.className = 'breach-status error';
        statusEl.innerHTML = '<span class="breach-icon">⚠️</span> Erreur de connexion';
        safeLog(`Breach check error: ${err.message}`);
      } finally {
        btn.classList.remove('checking');
        btn.disabled = false;
      }
    }, { signal: eventController.signal });
  });
}

/**
 * Show context menu for password actions
 */
function showContextMenu(e, password) {
  // Remove any existing context menu
  const existing = document.querySelector('.pwd-context-menu');
  if (existing) existing.remove();

  const vaultAvailable = VaultBridge.isAvailable();

  const menu = document.createElement('div');
  menu.className = 'pwd-context-menu';
  menu.innerHTML = `
    <button class="pwd-ctx-item" data-action="copy">
      <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2">
        <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
      </svg>
      Copier
    </button>
    ${vaultAvailable ? `
      <button class="pwd-ctx-item" data-action="save-vault">
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2">
          <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
          <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
        </svg>
        Sauvegarder dans le coffre
      </button>
    ` : ''}
  `;

  // Position menu at cursor
  menu.style.left = `${e.clientX}px`;
  menu.style.top = `${e.clientY}px`;

  document.body.appendChild(menu);

  // Bind menu actions
  menu.querySelectorAll('.pwd-ctx-item').forEach(item => {
    item.addEventListener('click', async () => {
      const action = item.getAttribute('data-action');

      if (action === 'copy') {
        const success = await copyToClipboard(password);
        if (success) {
          showToast('Mot de passe copié !', 'success');
        } else {
          showToast('Erreur lors de la copie', 'error');
        }
      } else if (action === 'save-vault') {
        await SaveToVaultModal.open(password);
      }

      menu.remove();
    });
  });

  // Cleanup function to remove all menu listeners
  const cleanupMenu = () => {
    menu.remove();
    document.removeEventListener('click', closeMenu);
    document.removeEventListener('keydown', escHandler);
  };

  // Close on click outside
  const closeMenu = (ev) => {
    if (!menu.contains(ev.target)) {
      cleanupMenu();
    }
  };

  // Close on escape
  const escHandler = (ev) => {
    if (ev.key === 'Escape') {
      cleanupMenu();
    }
  };

  setTimeout(() => {
    document.addEventListener('click', closeMenu);
    document.addEventListener('keydown', escHandler);
  }, 0);
}

/**
 * Cleanup all password card event listeners
 * Uses AbortController for automatic removal of all tracked listeners
 * Also clears any pending click timers
 */
function cleanupPasswordListeners() {
  // Abort all listeners registered with the current controller
  eventController.abort();

  // Create new controller for next batch of listeners
  eventController = new AbortController();

  // Clear any pending click timers
  document.querySelectorAll('.pwd').forEach(el => {
    const timer = clickTimers.get(el);
    if (timer) {
      clearTimeout(timer);
      clickTimers.delete(el);
    }
  });

  safeLog('Password card listeners cleaned up');
}

export function updateMaskDisplay(mask) {
  document.querySelectorAll('.pwd').forEach(el => {
    el.classList.toggle('masked', mask);
  });
}

export function renderEmptyState() {
  const wrap = getElement('#results-list');
  if (wrap) {
    wrap.innerHTML = sanitizeHTML(`
      <div class="empty-state">
        <div class="empty-icon">🔐</div>
        <p>Cliquez sur "Générer" pour créer vos mots de passe</p>
      </div>`);
  }
}
