import { safeLog } from '../utils/logger.js';

/**
 * AliasService - Manage Email Aliases (Hide-My-Email)
 * Integrates with SimpleLogin and AnonAddy APIs
 */
export class AliasService {
    static PROVIDERS = {
        SIMPLELOGIN: { id: 'simplelogin', name: 'SimpleLogin', apiUrl: 'https://app.simplelogin.io/api' },
        ANONADDY: { id: 'anonaddy', name: 'AnonAddy', apiUrl: 'https://app.anonaddy.com/api/v1' }
    };

    #apiKey = null;
    #provider = null;
    #hostname = null; // Included in generated alias if easy-mode

    constructor() {
        this.#loadConfig();
    }

    async #loadConfig() {
        const storedConfig = localStorage.getItem('alias_service_config');
        if (storedConfig) {
            try {
                const config = JSON.parse(storedConfig);
                this.#provider = config.provider || AliasService.PROVIDERS.SIMPLELOGIN.id;

                // Decrypt API key if present
                if (config.encryptedKey && window.electronAPI) {
                    try {
                        this.#apiKey = await window.electronAPI.decryptSecret(config.encryptedKey);
                    } catch (e) {
                        safeLog('Failed to decrypt alias API key', e);
                    }
                }
            } catch (e) {
                safeLog('Failed to parse alias config', e);
            }
        }
    }

    async saveConfig(providerId, apiKey) {
        let config;

        if (window.electronAPI?.encryptSecret) {
            // Electron: Use secure storage
            const encryptedKey = await window.electronAPI.encryptSecret(apiKey);
            config = {
                provider: providerId,
                encryptedKey: encryptedKey
            };
        } else {
            // Web mode: Store in localStorage (less secure, warn user)
            safeLog('[AliasService] Warning: Secure storage not available, using localStorage');
            config = {
                provider: providerId,
                // In web mode, we store a flag but NOT the API key itself
                // User will need to re-enter it each session
                webModeNoStorage: true
            };
            // Keep in memory only for this session
            this.#apiKey = apiKey;
        }

        localStorage.setItem('alias_service_config', JSON.stringify(config));
        this.#provider = providerId;

        if (config.encryptedKey) {
            this.#apiKey = apiKey;
        }
        return true;
    }

    get isConfigured() {
        return !!this.#apiKey;
    }

    get providerName() {
        return this.#provider === 'anonaddy' ? 'AnonAddy' : 'SimpleLogin';
    }

    /**
     * Validate API Key by fetching user info
     */
    async validateApiKey(providerId, apiKey) {
        const provider = Object.values(AliasService.PROVIDERS).find(p => p.id === providerId);
        if (!provider) throw new Error('Invalid provider');

        let endpoint = '';
        let headers = {};

        if (providerId === 'simplelogin') {
            endpoint = `${provider.apiUrl}/user_info`;
            headers = { 'Authentication': apiKey };
        } else if (providerId === 'anonaddy') {
            endpoint = `${provider.apiUrl}/account-details`;
            headers = { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest' };
        }

        try {
            const response = await fetch(endpoint, { method: 'GET', headers });
            if (!response.ok) throw new Error(`API Error: ${response.status}`);
            await response.json(); // Validate JSON response
            return true;
        } catch (error) {
            safeLog('Alias API Validation Failed:', error);
            return false;
        }
    }

    /**
     * Generate a new random alias
     * @param {string} note - Optional note/label for the alias (e.g. Service Name)
     */
    async generateAlias(note = 'Generated by GenPwd Pro') {
        if (!this.#apiKey) throw new Error('Service not configured');

        const providerId = this.#provider || 'simplelogin';
        const provider = Object.values(AliasService.PROVIDERS).find(p => p.id === providerId);

        let endpoint = '';
        let method = 'POST';
        let headers = {};
        let body = null;

        if (providerId === 'simplelogin') {
            // SimpleLogin: POST /api/alias/random/new
            // Note: "note" field is supported in some endpoints, but random/new might be simple
            // Better to use /api/v2/alias/custom/new if we want to specify domain, but random is safer for free tier
            endpoint = `${provider.apiUrl}/alias/random/new`;
            headers = { 'Authentication': this.#apiKey, 'Content-Type': 'application/json' };
            body = JSON.stringify({ note: note, hostname: null }); // hostname can be used for suggestion
        } else if (providerId === 'anonaddy') {
            // AnonAddy: POST /api/v1/aliases
            endpoint = `${provider.apiUrl}/aliases`;
            headers = { 'Authorization': `Bearer ${this.#apiKey}`, 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest' };
            body = JSON.stringify({ description: note, format: 'uuid' }); // uuid creates random
        }

        try {
            const response = await fetch(endpoint, { method, headers, body });
            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Generation Failed: ${response.status} - ${errText}`);
            }

            const data = await response.json();

            // Normalize result
            if (providerId === 'simplelogin') {
                return data.alias; // { alias: "...", ... }
            } else if (providerId === 'anonaddy') {
                return data.data.email; // { data: { email: "...", ... } }
            }
        } catch (error) {
            safeLog('Alias Generation Error:', error);
            throw error;
        }
    }
}
