#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANDROID_PROJECT_DIR="${REPO_ROOT}/android"
SDK_ROOT="${ANDROID_SDK_ROOT:-/opt/android-sdk}"
SDKMANAGER="${SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"

if [[ ! -x "${SDKMANAGER}" ]]; then
  echo "sdkmanager not found at ${SDKMANAGER}. Did the Docker image install commandline-tools?" >&2
  exit 1
fi

mkdir -p "${SDK_ROOT}" "${ANDROID_PROJECT_DIR}"

PACKAGES=(
  "platform-tools"
  "platforms;android-34"
  "build-tools;34.0.0"
)

echo "Accepting Android SDK licenses..."
(yes | "${SDKMANAGER}" --sdk_root="${SDK_ROOT}" --licenses >/dev/null) || true

echo "Installing Android SDK packages..."
"${SDKMANAGER}" --sdk_root="${SDK_ROOT}" "${PACKAGES[@]}"

LOCAL_PROPERTIES_FILE="${ANDROID_PROJECT_DIR}/local.properties"
SDK_DIR_VALUE="${SDK_ROOT}"
# Escape backslashes and spaces for local.properties compatibility.
SDK_DIR_VALUE="${SDK_DIR_VALUE//\/\\}"
SDK_DIR_VALUE="${SDK_DIR_VALUE// /\\ }"

cat > "${LOCAL_PROPERTIES_FILE}" <<EOF_PROPERTIES
## Generated by setup-android-sdk.sh. Do not edit manually.
sdk.dir=${SDK_DIR_VALUE}
EOF_PROPERTIES

chmod +x "${ANDROID_PROJECT_DIR}/gradlew"

echo "Android SDK setup complete. local.properties written to ${LOCAL_PROPERTIES_FILE}."
