#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: setup-android-sdk.sh [options]

Options:
  --sdk-root <path>           Android SDK root directory. Defaults to $ANDROID_SDK_ROOT or /opt/android-sdk.
  --project-root <path>       Project directory where local.properties should be written. Defaults to the
                              Android module directory relative to this script when run from the repository.
  --skip-local-properties     Do not create or update local.properties.
  -h, --help                  Show this help message.
USAGE
}

SDK_ROOT=${ANDROID_SDK_ROOT:-/opt/android-sdk}
PROJECT_ROOT=""
WRITE_LOCAL_PROPERTIES=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sdk-root)
            SDK_ROOT=$2
            shift 2
            ;;
        --project-root)
            PROJECT_ROOT=$2
            shift 2
            ;;
        --skip-local-properties)
            WRITE_LOCAL_PROPERTIES=false
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [[ -z "$PROJECT_ROOT" ]]; then
    SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    PROJECT_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)/android
fi

SDKMANAGER_BIN="$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
if [[ ! -x "$SDKMANAGER_BIN" ]]; then
    echo "Android cmdline-tools not found at $SDKMANAGER_BIN" >&2
    exit 1
fi

PACKAGES=(
    "platform-tools"
    "build-tools;34.0.0"
    "platforms;android-34"
)

echo "Accepting Android SDK licenses..."
yes | "$SDKMANAGER_BIN" --sdk_root="$SDK_ROOT" --licenses >/dev/null

echo "Updating sdkmanager..."
"$SDKMANAGER_BIN" --sdk_root="$SDK_ROOT" --update >/dev/null

echo "Installing required Android SDK packages..."
"$SDKMANAGER_BIN" --sdk_root="$SDK_ROOT" --install "${PACKAGES[@]}"

if [[ "$WRITE_LOCAL_PROPERTIES" == true ]]; then
    mkdir -p "$PROJECT_ROOT"
    SDK_PATH_ESCAPED=${SDK_ROOT//\\/\\\\}
    SDK_PATH_ESCAPED=${SDK_PATH_ESCAPED// /\\ }
    cat > "$PROJECT_ROOT/local.properties" <<EOF_PROPERTIES
# Generated by setup-android-sdk.sh
sdk.dir=$SDK_PATH_ESCAPED
EOF_PROPERTIES
    echo "local.properties written to $PROJECT_ROOT/local.properties"
else
    echo "Skipping local.properties generation."
fi

