name: Android CI

on:
  push:
    branches: [ main, develop, feature/**, fix/**, hotfix/** ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required SDK packages
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Show tool versions
        run: |
          ./gradlew --version
          sdkmanager --list | head -n 50

      - name: Run lint checks (vital fallback to release)
        run: |
          ./gradlew :app:lintVitalRelease || true
          ./gradlew :app:lintRelease

      - name: Assemble release build
        run: ./gradlew :app:assembleRelease

      - name: Upload release artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/**/*.apk
