name: Android CI

on:
  push:
    branches: [ main, android/** ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"
      - run: ./gradlew assembleDebug --no-daemon
        working-directory: android

  static-checks:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"
      - name: Run linting, static analysis and tests
        run: ./gradlew lint ktlintCheck detekt test --no-daemon
        working-directory: android
